server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:h2:mem:musala
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
